apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-kubeflow-user-example-com-kubeflow-edit
  ## this RoleBinding is in `kubeflow`, because it grants access to `kubeflow`
  namespace: kubeflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeflow-edit
subjects:
  - kind: ServiceAccount
    name: default-editor
    ## the ServiceAccount lives in `kubeflow-user-example-com`
    namespace: kubeflow-user-example-com