apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "bankchurn"
  namespace: "bankchurn-kserve"
spec:
  predictor:
    serviceAccountName: sa
    model:
      modelFormat:
        name: mlflow
      protocolVersion: v2
      storageUri: "s3://httt/4/0fc9acb8179446b79758fbfcd66e0919/artifacts/model/"