apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: bankchurn-model
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  predictor:
    serviceAccountName: sa-minio-kserve
    model:
      modelFormat:
        name: mlflow
      protocolVersion: v2 # Use V2 inference protocol for MLflow models
      storageUri: "s3://mlflow-artifacts/1/d88a93df67ac4d8282894ebeadc0956a/artifacts/model/" # Path to your model in MinIO