# Create a Service Account , we named the file as create - s3 - sa . yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
  annotations:
    serving.kserve.io/s3-endpoint: 10.43.136.100:9000
    serving.kserve.io/s3-usehttps: "0"
    serving.kserve.io/s3-useanoncredential: "false"
